version: "3.8"
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - mongo

  worker:
    build: ./worker
    depends_on:
      - rabbitmq
      - mongo

  vendor-sync:
    build: ./vendor-mocks/sync
    ports:
      - "4001:4001"

  vendor-async:
    build: ./vendor-mocks/async
    ports:
      - "4002:4002"

  webhook:
    build: ./webhook
    ports:
      - "5050:5000"
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
